# Generated by Django 5.0.6 on 2024-07-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('CANCELADO', 'Cancelado'), ('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='region',
            field=models.CharField(choices=[('LOS_LAGOS', 'Región de Los Lagos'), ('O_HIGGINS', "Región de O'Higgins"), ('MAGALLANES', 'Región de Magallanes'), ('VALPARAISO', 'Región de Valparaíso'), ('BIOBIO', 'Región del Biobío'), ('ARICA_PARINACOTA', 'Región de Arica y Parinacota'), ('ARAUCANIA', 'Región de La Araucanía'), ('ÑUBLE', 'Región de Ñuble'), ('MAULE', 'Región del Maule'), ('COQUIMBO', 'Región de Coquimbo'), ('TARAPACA', 'Región de Tarapacá'), ('AYSEN', 'Región de Aysén'), ('LOS_RIOS', 'Región de Los Ríos'), ('ANTOFAGASTA', 'Región de Antofagasta'), ('METROPOLITANA', 'Región Metropolitana'), ('ATACAMA', 'Región de Atacama')], default='CONCEPCION', max_length=25),
        ),
        migrations.AlterField(
            model_name='persona',
            name='region',
            field=models.CharField(choices=[('LOS_LAGOS', 'Región de Los Lagos'), ('O_HIGGINS', "Región de O'Higgins"), ('MAGALLANES', 'Región de Magallanes'), ('VALPARAISO', 'Región de Valparaíso'), ('BIOBIO', 'Región del Biobío'), ('ARICA_PARINACOTA', 'Región de Arica y Parinacota'), ('ARAUCANIA', 'Región de La Araucanía'), ('ÑUBLE', 'Región de Ñuble'), ('MAULE', 'Región del Maule'), ('COQUIMBO', 'Región de Coquimbo'), ('TARAPACA', 'Región de Tarapacá'), ('AYSEN', 'Región de Aysén'), ('LOS_RIOS', 'Región de Los Ríos'), ('ANTOFAGASTA', 'Región de Antofagasta'), ('METROPOLITANA', 'Región Metropolitana'), ('ATACAMA', 'Región de Atacama')], default='CONCEPCION', max_length=25),
        ),
    ]
