# Generated by Django 5.0.6 on 2024-07-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_carrito_subtotal_alter_envio_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='region',
            field=models.CharField(choices=[('O_HIGGINS', "Región de O'Higgins"), ('ATACAMA', 'Región de Atacama'), ('LOS_RIOS', 'Región de Los Ríos'), ('LOS_LAGOS', 'Región de Los Lagos'), ('ARICA_PARINACOTA', 'Región de Arica y Parinacota'), ('MAULE', 'Región del Maule'), ('TARAPACA', 'Región de Tarapacá'), ('BIOBIO', 'Región del Biobío'), ('MAGALLANES', 'Región de Magallanes'), ('VALPARAISO', 'Región de Valparaíso'), ('METROPOLITANA', 'Región Metropolitana'), ('AYSEN', 'Región de Aysén'), ('ÑUBLE', 'Región de Ñuble'), ('COQUIMBO', 'Región de Coquimbo'), ('ARAUCANIA', 'Región de La Araucanía'), ('ANTOFAGASTA', 'Región de Antofagasta')], default='CONCEPCION', max_length=25),
        ),
        migrations.AlterField(
            model_name='persona',
            name='region',
            field=models.CharField(choices=[('O_HIGGINS', "Región de O'Higgins"), ('ATACAMA', 'Región de Atacama'), ('LOS_RIOS', 'Región de Los Ríos'), ('LOS_LAGOS', 'Región de Los Lagos'), ('ARICA_PARINACOTA', 'Región de Arica y Parinacota'), ('MAULE', 'Región del Maule'), ('TARAPACA', 'Región de Tarapacá'), ('BIOBIO', 'Región del Biobío'), ('MAGALLANES', 'Región de Magallanes'), ('VALPARAISO', 'Región de Valparaíso'), ('METROPOLITANA', 'Región Metropolitana'), ('AYSEN', 'Región de Aysén'), ('ÑUBLE', 'Región de Ñuble'), ('COQUIMBO', 'Región de Coquimbo'), ('ARAUCANIA', 'Región de La Araucanía'), ('ANTOFAGASTA', 'Región de Antofagasta')], default='CONCEPCION', max_length=25),
        ),
    ]
