# Generated by Django 5.0.6 on 2024-07-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_remove_carrito_subtotal_alter_envio_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('ENTREGADO', 'Entregado'), ('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='region',
            field=models.CharField(choices=[('VALPARAISO', 'Región de Valparaíso'), ('AYSEN', 'Región de Aysén'), ('O_HIGGINS', "Región de O'Higgins"), ('MAULE', 'Región del Maule'), ('ÑUBLE', 'Región de Ñuble'), ('LOS_LAGOS', 'Región de Los Lagos'), ('ARAUCANIA', 'Región de La Araucanía'), ('LOS_RIOS', 'Región de Los Ríos'), ('BIOBIO', 'Región del Biobío'), ('ANTOFAGASTA', 'Región de Antofagasta'), ('ARICA_PARINACOTA', 'Región de Arica y Parinacota'), ('MAGALLANES', 'Región de Magallanes'), ('TARAPACA', 'Región de Tarapacá'), ('COQUIMBO', 'Región de Coquimbo'), ('ATACAMA', 'Región de Atacama'), ('METROPOLITANA', 'Región Metropolitana')], default='CONCEPCION', max_length=25),
        ),
        migrations.AlterField(
            model_name='persona',
            name='region',
            field=models.CharField(choices=[('VALPARAISO', 'Región de Valparaíso'), ('AYSEN', 'Región de Aysén'), ('O_HIGGINS', "Región de O'Higgins"), ('MAULE', 'Región del Maule'), ('ÑUBLE', 'Región de Ñuble'), ('LOS_LAGOS', 'Región de Los Lagos'), ('ARAUCANIA', 'Región de La Araucanía'), ('LOS_RIOS', 'Región de Los Ríos'), ('BIOBIO', 'Región del Biobío'), ('ANTOFAGASTA', 'Región de Antofagasta'), ('ARICA_PARINACOTA', 'Región de Arica y Parinacota'), ('MAGALLANES', 'Región de Magallanes'), ('TARAPACA', 'Región de Tarapacá'), ('COQUIMBO', 'Región de Coquimbo'), ('ATACAMA', 'Región de Atacama'), ('METROPOLITANA', 'Región Metropolitana')], default='CONCEPCION', max_length=25),
        ),
    ]
